
services:
  backend_dolanan:
    container_name: dolanan
    build: .
    volumes:
      - ./dolanan:/var/www/html
    ports:
      - 2000:80
    networks:
      - dolanan-network


  db:
    image: mariadb:latest
    container_name: dolanan-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 200400
      MYSQL_DATABASE: dolanan
      MYSQL_USER: lukmanhadi20
      MYSQL_PASSWORD: 200400
    volumes:
      - db_data:/var/lib/mysql  
    ports:
      - 3306:3306            
    networks:
      - dolanan-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dolanan-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: lukmanhadi20
      PMA_PASSWORD: 200400
      PMA_PORT: 3306
    ports:
      - 8082:80                
    depends_on:
      - db
    networks:
      - dolanan-network

volumes:
  db_data:                     
networks:
  dolanan-network:
    driver: bridge             

